spring:
  application:
    name: pdfanalyser
  ai:
    model:
      chat: ollama
      embedding: ollama
    google:
      genai:
        api-key: YOUR_GOOGLE_GENAI_API_KEY
        chat:
          options:
            model: gemini-2.5-flash
            temperature: 0.7
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 768
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
            table-name: chat_memory

  datasource:
    url: jdbc:postgresql://localhost:5434/vector-db
    username: your-username
    password: your-password
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG
